# Generated by Django 3.2.4 on 2021-06-24 02:32

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone
from user.models import CustomUser

class Migration(migrations.Migration):
    def seed_data(apps, schema_editor):
        user = CustomUser(name='name',
                          email='sanketmmcc@gmail.com',
                          is_staff=True,
                          is_superuser=True,
                          phone='8484933041',
                          gender='Male'

                          )
        user.set_password('1234')
        user.save()

    dependencies = [
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
